
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-16
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-16
pull_requests: [{"author":{"id":"U_kgDOC31Aag","is_bot":false,"login":"alexjh2","name":""},"headRefName":"aj-addlauncher","number":12,"title":"Add RecordCommonStats job launcher, form, and tests","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-16/pull/12"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn-redesign-admin-list-commons-page","number":11,"title":"replace table on admin/listcommons page with cards","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-16/pull/11"},{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-admin-info-page","number":10,"title":"added admin/developer info page and tests","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-16/pull/10"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-chat-message-pagination","number":9,"title":"Chat Message Pagination","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-16/pull/9"}]
